
select * from customer_shopping_behavior limit 20

--Q1: What is the revenue generated by the male vs female customers?
select 
	gender, 
	SUM(purchase_amount) as revenue 
	
from customer_shopping_behavior
group by gender;


--Q2: which customer used a discount but still spent more than the average purchase anount?
select 
	customer_id, 
	purchase_amount 
	
from customer_shopping_behavior
where discount_applied = 'Yes' and purchase_amount >  ( select AVG( purchase_amount ) from customer_shopping_behavior)


--Q3: which are the top 5 product with highest average review rating?
select 
	item_purchased, 
	Round(AVG(review_rating)::numeric, 2) as average_review_rating
	
from customer_shopping_behavior
group by item_purchased
order by average_review_rating desc
limit 5;


--Q4: compare the average purchase amount between standard and express shipping.
select 
	shipping_type, 
	ROUND( AVG( purchase_amount ), 2)
	
from customer_shopping_behavior
where shipping_type IN('Standard', 'Express')
group by shipping_type;


--Q5: Do subscribed customer spend more? compare average spend and total revenue btw subscribers and non-subscribers.
select 
	subscription_status, 
	COUNT( customer_id ) as total_customers, 
	Round( AVG( purchase_amount ), 2) as average_spend,
	Round( SUM( purchase_amount), 2) as total_revenue 
	
from customer_shopping_behavior
group by subscription_status
order by total_revenue, average_spend desc;


--Q6: which 5 products have the highest purchase percentage with discount applied?
select 
	item_purchased, 
	COUNT(*) as total_item_purchased, 
	SUM( purchase_amount ) as total_revenue,
	Round(SUM( purchase_amount ) * 100 / SUM( SUM( purchase_amount)) over() , 2) as revenue_percentage

from customer_shopping_behavior
where discount_applied = 'Yes'
group by item_purchased 
order by sum( purchase_amount ) desc limit 5;


--q7: segment customers into New, Returning and Loyal based on their total number of 
--    previous purchases amd show to count of each segment?
with segmented_customers As (
	select 
		case 
			when previous_purchases in (0, 1) then 'new'
			when previous_purchases between 2 and 6 then 'Returning'
			else 'Loyal'
		end as customer_segment
	from customer_shopping_behavior
)
select 
	customer_segment,
	count(*) as total_customers
	
from segmented_customers 
group by customer_segment
order by total_customers desc;



--Q8: what are the top 3 most purchased product within each category?
with items_count AS (
		select 
			category,
			ROW_NUMBER() over(
				PARTITION BY category
				order by count(*) desc 
			) as product_rank,
			item_purchased,
			COUNt(*) as total_orders,
			SUM( purchase_amount ) as total_revenue
		from customer_shopping_behavior
		Group by category, item_purchased
)
select * from items_count
where product_rank <= 3
order by category, product_rank ;


--Q9: Are customers who are repeat buyers ( more than 5 previous purchases ) also likely to subscribe?
select 
	subscription_status,
	count(customer_id) as repeated_buyers

from customer_shopping_behavior
where previous_purchases > 5
group by subscription_status;


--Q10: what is the revenue contribution of each gruop?
select 
	age_group,
	Round( SUM( purchase_amount )) as revenue

from customer_shopping_behavior
group by age_group
order by revenue desc;
	